♻️ci: use GITHUB_ENV instead of GITHUB_OUTPUT

diff --git a/.github/workflows/bun-test.yml b/.github/workflows/bun-test.yml
--- a/.github/workflows/bun-test.yml
+++ b/.github/workflows/bun-test.yml
@@ -42,4 +42,70 @@ jobs:
         run: bun i
 
       - name: Test app
-        run: bun test
+        run: |
+          bun test &> >(tee -p test.log) || echo STATUS=$? >> $GITHUB_ENV
+          {
+            echo 'RESULT<<EOF'
+            cat test.log
+            echo EOF
+          } >> $GITHUB_ENV
+
+      - name: Create test comment
+        if: github.event_name == 'pull_request' && env.STATUS == 1
+        env:
+          ACTOR: ${{ github.actor }}
+          REPO: ${{ github.repository }}
+          RUN_ID: ${{ github.run_id }}
+          SHA: ${{ github.event.pull_request.head.sha }}
+          WORKFLOW_REF: ${{ github.workflow_ref }}
+        run: |
+          {
+            echo 'TEST_COMMENT<<EOF'
+            echo '# ❌Test Failed'
+            echo "@$ACTOR, your commit $SHA failed the test."
+            echo '<details>'
+            echo '<summary><strong>Test Log</strong></summary>'
+            echo ''
+            echo "\`\`\`shell"
+            echo "$RESULT"
+            echo "\`\`\`"
+            echo ''
+            echo '</details>'
+            echo ''
+            echo "👀[View in Actions](https://github.com/$REPO/actions/runs/$RUN_ID)"
+            echo "<!-- generated-comment [Bun CI]($WORKFLOW_REF) -->"
+            echo 'EOF'
+          } >> $GITHUB_ENV
+
+      - name: Update or Add a test comment
+        if: github.event_name == 'pull_request' && env.STATUS == 1
+        uses: actions/github-script@v7
+        with:
+          script: |
+            const { data: comments } = await github.rest.issues.listComments({
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              issue_number: context.issue.number,
+            })
+            const testComment = comments.find(comment => {
+              return comment.user.type === 'Bot' && comment.body.includes('# ❌Test Failed')
+            })
+            if (testComment) {
+              github.rest.issues.updateComment({
+                owner: context.repo.owner,
+                repo: context.repo.repo,
+                comment_id: testComment.id,
+                body: process.env.TEST_COMMENT
+              })
+            } else {
+              github.rest.issues.createComment({
+                issue_number: context.issue.number,
+                owner: context.repo.owner,
+                repo: context.repo.repo,
+                body: process.env.TEST_COMMENT
+              })
+            }
+
+      - name: Fail if test failed
+        if: env.STATUS == 1
+        run: exit 1
