ci: update commitlint.yaml

diff --git a/.github/workflows/commitlint.yml b/.github/workflows/commitlint.yml
--- a/.github/workflows/commitlint.yml
+++ b/.github/workflows/commitlint.yml
@@ -6,11 +6,12 @@ concurrency:
 
 on:
   push:
-  pull_request:
+  pull_request_target:
   workflow_dispatch:
 
 permissions:
   contents: read
+  pull-requests: write
 
 jobs:
   commitlint:
@@ -21,7 +22,7 @@ jobs:
       - name: 📥 Checkout
         uses: actions/checkout@v4
         with:
-          fetch-depth: 0
+          ref: ${{ github.event.pull_request.head.sha || github.sha }}
       - name: 🐣 Install bun
         uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76
         with:
@@ -31,12 +32,105 @@ jobs:
       - name: 📝 Create commitlint config
         run: |
           echo 'export default { extends: ["@commitlint/config-conventional"],
-          ignores: [(message) => message.includes("Signed-off-by: dependabot[bot]")] }' > commitlint.config.ts
+          ignores: [(message: string) => message.includes("Signed-off-by: dependabot[bot]")] }' > commitlint.config.ts
 
       - name: 👀 Validate current commit (last commit) with commitlint
         if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
         run: bunx commitlint --last --verbose
 
       - name: 👀 Validate PR commits with commitlint
-        if: github.event_name == 'pull_request'
-        run: bunx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
+        if: github.event_name == 'pull_request_target'
+        env:
+          BASE_SHA: ${{ github.event.pull_request.base.sha }}
+          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
+        run: |
+          bunx commitlint --from $BASE_SHA --to $HEAD_SHA --verbose \
+          &> >(tee -p commitlint.log) || echo STATUS=$? >> $GITHUB_ENV
+          {
+            echo 'RESULT<<EOF'
+            cat commitlint.log
+            echo EOF
+          } >> $GITHUB_ENV
+
+      - name: ❌ Add a commitlint comment
+        if: github.event_name == 'pull_request_target' && env.STATUS == 1
+        uses: actions/github-script@v7
+        env:
+          ACTOR: ${{ github.actor }}
+          REPO: ${{ github.repository }}
+          RUN_ID: ${{ github.run_id }}
+          SHA: ${{ github.event.pull_request.head.sha }}
+          WORKFLOW_REF: ${{ github.workflow_ref }}
+        with:
+          script: |
+            const { data: comments } = await github.rest.issues.listComments({
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              issue_number: context.issue.number,
+            })
+            const commitlintComment = comments.find(comment => {
+              return comment.user.type === 'Bot' && comment.body.includes('# ❌ Commitlint Failed')
+            })
+
+            const body = `# ❌ Commitlint Failed
+            @$ACTOR, your commit $SHA failed the commitlint check.
+
+            <details>
+            <summary><strong>Commitlint Log</strong></summary>
+
+            \`\`\`shell
+            $RESULT
+            \`\`\`
+
+            </details>
+
+            Please update the commit message to follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/).
+            👀[View in Actions](https://github.com/$REPO/actions/runs/$RUN_ID)
+            <!-- generated-comment [Commitlint]($WORKFLOW_REF) -->`
+
+            if (commitlintComment) {
+              await github.rest.issues.deleteComment({
+                owner: context.repo.owner,
+                repo: context.repo.repo,
+                comment_id: commitlintComment.id,
+              })
+            }
+            await github.rest.issues.createComment({
+              issue_number: context.issue.number,
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              body: body
+            })
+
+      - name: ✅ Add a Fixed comment
+        uses: actions/github-script@v7
+        if: github.event_name == 'pull_request_target' && env.STATUS == 0
+        env:
+          WORKFLOW_REF: ${{ github.workflow_ref }}
+        with:
+          script: |
+            const { data: comments } = await github.rest.issues.listComments({
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              issue_number: context.issue.number,
+            })
+            const commitlintComment = comments.find(comment => {
+              return comment.user.type === 'Bot' && comment.body.includes('# ❌ Commitlint Failed')
+            })
+            const body = `# ✅ Commitlint Passed
+            Thank you for updating the commit message to follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/).
+            <!-- generated-comment [Commitlint]($WORKFLOW_REF) -->`
+
+            if (commitlintComment) {
+              await github.rest.issues.deleteComment({
+                owner: context.repo.owner,
+                repo: context.repo.repo,
+                comment_id: commitlintComment.id,
+              })
+              await github.rest.issues.createComment({
+                issue_number: context.issue.number,
+                owner: context.repo.owner,
+                repo: context.repo.repo,
+                body: body
+              })
+            }
