ci: check comment.yml (#613)
* ci: check comment.yml

* fix(autofix.ci): apply automated fixes

---------

Co-authored-by: autofix-ci[bot] <114827586+autofix-ci[bot]@users.noreply.github.com>

diff --git a/.github/workflows/pull-request-title-lint.yml b/.github/workflows/pull-request-title-lint.yml
--- a/.github/workflows/pull-request-title-lint.yml
+++ b/.github/workflows/pull-request-title-lint.yml
@@ -1,104 +1,127 @@
 name: ✨ Check Conventional Commit Title
 
 on:
-  pull_request_target:
+  pull_request:
     types:
       - opened
       - edited
       - reopened
 
 permissions:
-  pull-requests: write
+  contents: read
 
 jobs:
   lint-title:
     runs-on: ubuntu-latest
+    outputs:
+      did_fail: ${{ steps.commitlint.outputs.did_fail }}
+      commitlint_log: ${{ steps.commitlint.outputs.commitlint_log }}
     steps:
-      - name: 👀 Validate PR title
-        uses: amannn/action-semantic-pull-request@v5
-        id: lint_pr_title
+      - name: 📥 Checkout
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+      - name: 🐣 Install bun
+        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76
+        with:
+          bun-version: canary
+      - name: 📦 Install commitlint
+        run: bun add -d @commitlint/cli @commitlint/config-conventional
+      - name: 📝 Create commitlint config
+        run: |
+          echo 'export default { extends: ["@commitlint/config-conventional"],
+          ignores: [(message: string) => message.includes("Signed-off-by: dependabot[bot]")] }' > commitlint.config.ts
+
+      - name: 👀 Validate PR commits with commitlint
+        if: github.event_name == 'pull_request'
+        id: commitlint
         env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          TITLE: ${{ github.event.pull_request.title }}
+        run: |
+          echo "$TITLE" | bunx commitlint --verbose &> >(tee -p commitlint.log) || STATUS=$?
+          if [ $STATUS -ne 0 ]; then
+            echo "did_fail=1" >> $GITHUB_OUTPUT
+          else
+            echo "did_fail=0" >> $GITHUB_OUTPUT
+          fi
+          UUID=$(uuidgen)
+          {
+            echo "commitlint_log<<EOF_$UUID"
+            cat commitlint.log
+            echo "EOF_$UUID"
+          } >> $GITHUB_OUTPUT
+
+      - name: 💔 Fail if test failed
+        if: steps.commitlint.outputs.did_fail == '1'
+        run: exit 1
+
+
+  upload:
+    runs-on: ubuntu-latest
+    needs: lint-title
+    if: always()
+
+    steps:
+      - name: ❌ Create test failed comment
+        if: needs.lint-title.outputs.did_fail == '1'
+        env:
+          ACTOR: ${{ github.actor }}
+          COMMITLINT_LOG: ${{ needs.lint-title.outputs.commitlint_log }}
+          REPO: ${{ github.repository }}
+          RUN_ID: ${{ github.run_id }}
+          SHA: ${{ github.event.pull_request.head.sha }}
+        run: |
+          UUID=$(uuidgen)
+          cat <<EOF_$UUID > comment.txt
+          # ❌ Pull Request Title Linting Failed
+          @$ACTOR, thank you for opening this pull request 👋🏼
+          We require pull request titles to follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/) and it looks like your proposed title needs to be adjusted.
+
+          <details>
+          <summary><strong>Commitlint Log</strong></summary>
+
+          \`\`\`shell
+          $COMMITLINT_LOG
+          \`\`\`
+
+          </details>
+
+          Please update the title of this pull request to follow the specification.
+          👀[View in Actions](https://github.com/$REPO/actions/runs/$RUN_ID)
+          <!-- generated-comment [Lint-Title](https://github.com/$REPO/.github/workflows/commitlint.yml) -->
+          EOF_$UUID
+
+      - name: ✅ Create test success comment
+        if: needs.lint-title.outputs.did_fail == '0'
+        env:
+          REPO: ${{ github.repository }}
+        run: |
+          UUID=$(uuidgen)
+          cat <<EOF_$UUID > comment.txt
+          # ✅ Pull Request Title Linting Passed
+          Thank you for updating the title of this pull request to follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/).
+          <!-- generated-comment [Lint-Title](https://github.com/$REPO/.github/workflows/commitlint.yml) -->
+          EOF_$UUID
+
+      - name: 🔢 Create pull request number and title
+        env:
+          PR_NUMBER: ${{ github.event.pull_request.number }}
+        run: |
+          echo "$PR_NUMBER" > pr_number.txt
+          echo "# ❌ Pull Request Title Linting Failed" > title.txt
+
+      - name: 🆙 Upload test comment
+        uses: actions/upload-artifact@v4
         with:
-          types: |
-            build
-            chore
-            ci
-            docs
-            feat
-            fix
-            perf
-            refactor
-            revert
-            style
-            test
-
-      - name: ❌ Add a lint comment
-        uses: actions/github-script@v7
-        if: always() && (steps.lint_pr_title.outputs.error_message != null)
+          name: comment.txt
+          path: comment.txt
+      - name: 🆙 Upload pull request number
+        uses: actions/upload-artifact@v4
         with:
-          script: |
-            const { data: comments } = await github.rest.issues.listComments({
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              issue_number: context.issue.number,
-            })
-            const lintTitleComment = comments.find(comment => {
-              return comment.user.type === 'Bot' && comment.body.includes('# ❌ Pull Request Title Linting Failed')
-            })
-            const body = `# ❌ Pull Request Title Linting Failed
-            @${{ github.actor }}, thank you for opening this pull request 👋🏼
-            We require pull request titles to follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/) and it looks like your proposed title needs to be adjusted.
-
-            <details>
-            <summary><strong>Test Log</strong></summary>
-
-            \`\`\`shell
-            ${{ steps.lint_pr_title.outputs.error_message }}
-            \`\`\`
-
-            </details>
-
-            Please update the title of this pull request to follow the specification.
-            👀[View in Actions](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
-            <!-- generated-comment [Title-Lint](https://github.com/${{ github.repository }}/.github/workflows/pull-request-title-lint.yml) -->`
-
-            if (!lintTitleComment) {
-              await github.rest.issues.createComment({
-                owner: context.repo.owner,
-                repo: context.repo.repo,
-                issue_number: context.issue.number,
-                body: body
-              })
-            }
-
-      - name: ✅ Add a Fixed comment
-        uses: actions/github-script@v7
-        if: ${{ steps.lint_pr_title.outputs.error_message == null }}
+          name: pr_number.txt
+          path: pr_number.txt
+      - name: 🆙 Upload title
+        uses: actions/upload-artifact@v4
         with:
-          script: |
-            const { data: comments } = await github.rest.issues.listComments({
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              issue_number: context.issue.number,
-            })
-            const lintTitleComment = comments.find(comment => {
-              return comment.user.type === 'Bot' && comment.body.includes('# ❌ Pull Request Title Linting Failed')
-            })
-            const body = `# ✅ Pull Request Title Linting Passed
-            Thank you for updating the title of this pull request to follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/).
-            <!-- generated-comment [Title-Lint](${{ github.workflow_ref }}) -->`
-
-            if (lintTitleComment) {
-              await github.rest.issues.deleteComment({
-                owner: context.repo.owner,
-                repo: context.repo.repo,
-                comment_id: lintTitleComment.id,
-              })
-              await github.rest.issues.createComment({
-                owner: context.repo.owner,
-                repo: context.repo.repo,
-                issue_number: context.issue.number,
-                body: body
-              })
-            }
+          name: title.txt
+          path: title.txt
